### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by azaquaz** [PssbleTrngle/Skygrid#1]
**Describe the bug**
When minecraft is started up and this mod is installed, the game crashes.

**To Reproduce**
Install this mod. Start minecraft.

**Expected behavior**
I expect the game to start.

**Screenshots**
https://paste.dimdev.org/silatupoge.mccrash

**Version**
Please list forge and mod version
Forge 14.23.5.2815
Skygrid 1.0

**Comment by azaquaz** [comment]
Further information I just discovered: This does not happen if you have launched Minecraft WITHOUT this mod installed at least once, then install this and launch for real.

**Comment by PssbleTrngle** [comment]
Should be fixed in released version 1.1
