### ISSUE TITLE
Endless Levitation Bug on Entering Nether in SMP

### ISSUE THREAD

**Issue by BTRBT** [PssbleTrngle/Skygrid#13]
When falling into the void and being transported to the nether, players will often get a levitation buff that doesn't go away, and ascends them infinitely above the build height. Only solution is to disconnect and reconnect. Not sure why this is happening. Any advice? Great mod, btw.

**Comment by PssbleTrngle** [comment]
What to you mean with SMP?

I will try to recreate it as soon as I get to it and if I'm unable to, come back to you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BTRBT** [comment]
I'm very sorry for the delayed response and poor issue reporting on my part. I should have offered more detail, and precise wording. SMP = Survival multiplayer. 

I've done further testing, with _only_ skygrid installed, and the issue seems to have disappeared. I'm assuming it's a compatibility bug. I'll try testing a bit more in the next couple of days, and report back with my findings. 

One thing I do notice, however, is that falling through to the nether and being consumed by the void causes a lot of skipped ticks in single-player, and the client slows to the level of crashing but not closing out. Also get a lot of "Playername moved too quickly!" errors, but I'm not sure if that's really an issue with the mod, specifically.

Console also prints these error messages: https://pastebin.com/raw/826u80wT

I'm using skygrid-1.2.2, and forge 14.23.5.2824. Skygrid is the only mod installed on the test server, and it is locally hosted. Both the client and server are allocated between 1G and 2G of RAM. I'm not very good at Java yet, but if there's anything I can do to help, please let me know. 

Cheers!

**Comment by PssbleTrngle** [comment]
The errors you send me are no problem, they are just the model loader warning me that there is no model for my invisible frame block which spawns around liquid blocks.

Which mods did you use in the first attempt?

With "consumed by the void" I guess you mean falling down and dying, without entering the dimension below. Maybe there is something tick-related which costs to much processing time,  I will test around a bit.
