### ISSUE TITLE
Advent of Ascension default support

### ISSUE THREAD

**Issue by PssbleTrngle** [PssbleTrngle/Skygrid#14]
Create default support for the dimension from Advent of Ascension

**Comment by Dimentive** [comment]
I can’t wait! Advent of Ascension is a great mod.

**Comment by PssbleTrngle** [comment]
I am working on it, but I will release an update for the first few dimensions. AOA has so many and every single one of them needs time

**Comment by Dimentive** [comment]
Thanks for the updates. I love this mod! 😄
