### ISSUE TITLE
Version 1.3 crashes on startup

### ISSUE THREAD

**Issue by Dimentive** [PssbleTrngle/Skygrid#15]
Versions tested (Minecraft 1.12.2, of course):

Skygrid **1.3** (latest), Forge 14.23.5.2836 (latest) – Crashes.
Skygrid **1.3** (latest), Forge 14.23.5.2768 (recommended) – Crashes.
Skygrid **1.2.2**, Forge 14.23.5.2836 (latest) – Doesn’t crash.
Skygrid **1.2.2**, Forge 14.23.5.2768 (recommended) – Doesn’t crash.

[Crash report.](https://pastebin.com/raw/Lm3qfn21)

No mods other than Skygrid were used in these tests.

**Comment by PssbleTrngle** [comment]
Will fix it tomorrow just use v1.2.2 until then

**Comment by Dimentive** [comment]
Sure thing.

**Comment by Dimentive** [comment]
Sure thing. 👍

**Comment by PssbleTrngle** [comment]
Should work with version 1.3.1 now

**Comment by Dimentive** [comment]
Awesome. Thanks for the fix!
