### ISSUE TITLE
[Suggestions] Could support for these mods be added by default?

### ISSUE THREAD

**Issue by Dimentive** [PssbleTrngle/Skygrid#16]
Would you consider adding native support to these dimension-adding mods to Skygrid? They’re excellent and quite popular mods, so it would be great if you could.

* [The Aether II](https://minecraft.curseforge.com/projects/the-aether-ii) (adds 1 dimension)
* [AbyssalCraft](https://minecraft.curseforge.com/projects/abyssalcraft) (adds 4 dimensions)
* ~~[The Beneath](https://minecraft.curseforge.com/projects/the-beneath) (adds 1 dimension)~~
* ~~[Extra Utilities 2](https://minecraft.curseforge.com/projects/extra-utilities) (adds 1 dimension: the [Deep Dark](https://ftb.gamepedia.com/Deep_Dark))~~
* ~~[Hunting Dimension](https://minecraft.curseforge.com/projects/hunting-dimension) (adds 1 dimension)~~
* [The Betweenlands](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod) (adds 1 dimension)
* [Good Night’s Sleep](https://minecraft.curseforge.com/projects/good-nights-sleep) (adds 2 dimensions)

**Comment by PssbleTrngle** [comment]
Right now I am still working on the AoA3 dimensions, which will take a bit because there's lots of them and honestly its not the best work to do.
But I think do these first as they seem to be more important

**Comment by PssbleTrngle** [comment]
Hunting dimension, the beneath and the deep dark have been added

**Comment by Dimentive** [comment]
Awesome! Thank you. 👍
