### ISSUE TITLE
Game freezes when creating worlds with Phosphor installed

### ISSUE THREAD

**Issue by Dimentive** [PssbleTrngle/Skygrid#17]
If [Phosphor](https://minecraft.curseforge.com/projects/phosphor), a mod that improves Minecraft’s lighting engine to improve performance and decrease the time it takes to load chunks, is installed alongside Skygrid, the game will get stuck on “Building terrain” or just a background with no text when creating a world.

Worlds can be _loaded_ just fine, though; just not created.

This was tested in an instance with only Skygrid and Phosphor—no other mods.

**Log:** https://pastebin.com/raw/tKAAzQyD

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Skygrid:** [1.3.1](https://minecraft.curseforge.com/projects/skygrid/files/2702633) (latest)
* **Phosphor:** [0.2.2](https://minecraft.curseforge.com/projects/phosphor/files/2698698) (latest)

**Comment by Dimentive** [comment]
I disabled about half of the mods, and now, rather than being stuck on the regular background when creating a world, my game is stuck on “Building terrain” when creating a world.

Strange.

**Comment by PssbleTrngle** [comment]
Yes, I've heard about it, but I can't think of a compatibility problem right now.
Is this the entire log, it says nothing about world creation at all?

**Comment by Dimentive** [comment]
Yes, it’s the entire log, minus the spam caused by #18.

It doesn’t seem to mention any world creation errors, no.

**Comment by PssbleTrngle** [comment]
It does not mention anything from the point of the game being loaded and ready, thats the weird thing. "Itemstack injection complete" is usually the last thing printed before the minecraft start screen launches

**Comment by Dimentive** [comment]
This was fixed in version [0.2.4](https://minecraft.curseforge.com/projects/phosphor/files/2707000) of Phosphor!
