### ISSUE TITLE
Log spammed with “No block for” messages

### ISSUE THREAD

**Issue by Dimentive** [PssbleTrngle/Skygrid#18]
If one doesn’t have any mods that are supported by Skygrid installed, Skygrid spams the log with “There is no dimension with the name” and “No block for” messages at the bottom of the log.

Example: `[skygrid]: No block for "biomesoplenty:blood"`

This log is so large (9.51 MB) only because of these messages, so I couldn’t paste it anywhere. Hence, it’s an uploaded file:

* [**latest.log**](https://github.com/PssbleTrngle/Skygrid/files/3130272/latest.log)

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Skygrid:** [1.3.1](https://minecraft.curseforge.com/projects/skygrid/files/2702633) (latest)

**Comment by PssbleTrngle** [comment]
My bad, looks like a left a debug comment in. Will remove this in the next version
