### ISSUE TITLE
Problems using this with my server

### ISSUE THREAD

**Issue by FizzOnYourJaycee** [PssbleTrngle/Skygrid#2]
**Describe the bug**
My server does not run when I have this mod added. Runs perfectly fine without it. *Single player works 100% fine, it is just my server that is effected*

**To Reproduce**
Add the mod to my server mod folder and attempt to run it

**Expected behavior**
I expect my server to run with the skygrid world.

**Version**
Skygrid 1.1

**Comment by PssbleTrngle** [comment]
Does the server crash, and if so could you provide a crash report?
They can be found in _serverfolder/crash-reports_.

**Comment by FizzOnYourJaycee** [comment]
https://pastebin.com/5EDp31EP

**Comment by PssbleTrngle** [comment]
Ok thanks I know what to, should be fixed tomorrow

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FizzOnYourJaycee** [comment]
Sounds good, thank you.
