### ISSUE TITLE
Two questions about Skygrid

### ISSUE THREAD

**Issue by Dimentive** [PssbleTrngle/Skygrid#22]
1. Does every modded block that would normally spawn in a regular world spawn in a Skygrid world, or would I have to add each and every block that doesn’t have native support in Skygrid to its JSON files manually? And does every block spawn at the same Y level that it would normally spawn at?

2. Do villagers spawn anywhere in a Skygrid world?

**Comment by PssbleTrngle** [comment]
No most definitely not, but that was never the intention.
You would have to add the blocks in the json, but I thought about adding some kind of online config file creation tool to make that process easier.

The height does not affect what block will spawn where. The only exception is a 'floor' system I created where the generation for a dimension is split into several parts with different blocks (look at the tropicraft generation).

Villages do not spawn, what do you need them for?

**Comment by Dimentive** [comment]
Well, that’s a shame. It’s going to take a long time adding so many blocks to the JSON files. An online JSON file creation tool for Skygrid would be very useful, but would you consider adding a config option, disabled by default, that would add every block with world gen to the appropriate dimension JSON file? That’d be very convenient.

Also, are what blocks spawn where entirely random, aside from the block weights? And what do the weights mean? I’m assuming that higher weights mean that they’ll spawn more frequently.

**Comment by Dimentive** [comment]
Thanks for the quick response.

>You would have to add the blocks in the json

Well, that’s a shame. It’s going to take a long time adding so many blocks to the JSON files. An online JSON file creation tool for Skygrid would be very useful, but would you consider adding a config option, disabled by default, that would add every block with world gen to the appropriate dimension JSON file? That’d be very convenient.

Also, is what blocks spawn where entirely random, aside from the block weights?

Also also, why is there a second weight value within a block in the JSON files? That weight seems to always be 1. Does it just mean the weight in relation to the other blocks in that code block? I’m a bit confused.

Also also also, what does the `only_override` option do in the JSON files?

**Comment by Dimentive** [comment]
Another question: Since most metal blocks and ores—such as copper, tin, and silver—use their ore dictionaries in Skygrid’s dimension JSON file, which does it choose if there are multiple different kinds of copper ore, copper blocks, tin ore, tin blocks, etc., from various different mods in the pack?

Does it stick with one mod, or is it random? And does it vary depending on the ore? For instance, does only use copper, tin, silver, etc., ores and blocks from Thermal Expansion, or would I have to manually make it do that in the JSON files?

**Comment by PssbleTrngle** [comment]
The random selection is recursive, so a list of block can also can contain another list of blocks. That's why there are multiple nested weight values.

The generation is completely random and not affected by height or anything.

Only override is true per default. If it is set to false and the dimension it is representing is not available, it will be created.
That's how you add custom dimensions.

If I remember it right, it simply grabs the first ore dictionary entry. If thermalfoundation is the first for copper, it should be the first one for silver too, as they are added simultaneously.

**Comment by PssbleTrngle** [comment]
And I'm working on the online tool

**Comment by Dimentive** [comment]
That’s good to hear! Thank you so much for all the answers.

One last question (for now): Do passive mobs (sheeps, pigs, etc.) spawn anywhere in a Skygrid world? I’m assuming mobs don’t spawn aside from by mob spawners, which spawn in the world, but are there passive mob spawners in addition to hostile mob spawners? I only see one mob spawner in the JSON files, so I’m guessing they’re random?

**Comment by Dimentive** [comment]
That’s good to hear! I’m very excited about the online tool. It’ll make making my pack so much easier. Thank you so much for all the answers.

One last question (for now): Do passive mobs (sheeps, pigs, etc.) spawn anywhere in a Skygrid world? I’m assuming mobs don’t spawn aside from by mob spawners, which spawn in the world, but are there passive mob spawners in addition to hostile mob spawners? I only see one mob spawner in the JSON files, so I’m guessing they’re random?

**Comment by Dimentive** [comment]
That’s good to hear! I’m very excited about the online tool. It’ll make making my modpack so much easier. Thank you so much for all the answers.

One last question (for now): Do passive mobs (sheeps, pigs, etc.) spawn anywhere in a Skygrid world? I’m assuming mobs don’t spawn aside from by mob spawners, which spawn in the world, but are there passive mob spawners in addition to hostile mob spawners? I only see one mob spawner in the JSON files, so I’m guessing they’re random?

**Comment by PssbleTrngle** [comment]
The Mobs the spawners are defined in the config file too.

I don't know if hostile or passive mobs are spawning aside from that, but I don't block it on purpose
