### ISSUE TITLE
NullPointerException crash upon creating world

### ISSUE THREAD

**Issue by Dimentive** [PssbleTrngle/Skygrid#23]
It looks like my problems aren’t over yet. After updating to the latest version of Quark, my game no longer freezes when creating new worlds; however, my game crashes now:
`java.lang.NullPointerException: Exception in server tick loop`

**Full crash report:** https://pastebin.com/raw/TbZMRTGf

My game doesn’t crash or freeze with only Skygrid installed or with Skygrid and only a few mods installed. However, I have over 300 mods installed. Skygrid seems to be conflicting with one of them. I hope you can gather some information from the crash report that can help you figure out what mod is conflicting with Skygrid.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2816
* **Skygrid:** [1.4](https://minecraft.curseforge.com/projects/skygrid/files/2708212) (latest)

**Comment by PssbleTrngle** [comment]
Looks like a rather simple bug, should be fixed very soon

**Comment by PssbleTrngle** [comment]
I will upload a working version (1.4.1) which will catch these error and log them.
If you could test it and send me the log it would be very helpful.

**Comment by max961** [comment]
it did this with just jei optifine jornymap and tektopia mods on forge
