### ISSUE TITLE
Help Needed: How do I escape Limbo?

### ISSUE THREAD

**Issue by JumpyDragon** [PssbleTrngle/Skygrid#24]
Minecraft 1.12.2
Forge 14.23.5.2768 (also tried the newest, 14.23.5.2838)
Skygrid 1.4.1

Sorry if this is a dumb question, but I've fallen into Limbo, and don't have any way to teleport out. I tried killing myself, _repeatedly_, but I just reappear there... And since falling through the bottom just loops right back through Limbo again, the only way I can think of to die is by falling and hitting a bedrock block on the way down. Is there something else I should be trying?

**Comment by PssbleTrngle** [comment]
Oh damn, you should be able to escape it by dying, but it seems I made a mistake and qualified it as a respawn dimension.
Will fix it asap

**Comment by PssbleTrngle** [comment]
Uploaded a fix (version 1.4.2)
