### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by azaquaz** [PssbleTrngle/Skygrid#28]
**Describe the bug**
I'm still able to walk around, place and destroy blocks, but block drops stopped appearing, rightclicking (such as on crafting tables/getting rocks from garden of glass) stopped working, and anything typed and entered in chat didn't go through at all.
Trying to save & exit hangs indefinitely on the loading screen, so I had to force quit, therefore there was no crash log.

**To Reproduce**
It didn't happen immediately, I was able to get a bit done before it happened. Relaunching put me a bit back in time, just before I started bridging out with cobblestone in a straight line, I expect that's actually when the bug happened and I didn't immediately notice. It happened immediately on reloading the world though. I force exited one more time and removed this mod, then relaunched and opened the world and it ran fine, I was able to right click on the crafting table etc just fine.

If I wasn't able to get a crashlog, would the regular log be helpful at all? I'm afraid it's rather long. https://pastebin.com/JR0Th200

**Version**
Forge 31.1.74
Skygrid 2.4

**Comment by PssbleTrngle** [comment]
It happens every time you load the world with the mod?
And what other mods do you have installed?

**Comment by PssbleTrngle** [comment]
I just realised I can read the second one out of the log, I will do some testing with these mods.
Did you run it locally or via a server?

**Comment by azaquaz** [comment]
Locally, and yes, it happened every time I loaded with the mod, and stopped once I uninstalled it.

**Comment by PssbleTrngle** [comment]
Yes, it seems to happen if a spawner is generated.
I think i will have figured it out soon

**Comment by PssbleTrngle** [comment]
Should be fixed now in version 2.5

**Comment by PssbleTrngle** [comment]
Looking at the mods I saw a few which still need support, but I should fix that soon.
If you want to see the progress look at #30
