### ISSUE TITLE
Chest loot is identical

### ISSUE THREAD

**Issue by azaquaz** [PssbleTrngle/Skygrid#3]
**Describe the bug**
There are only a few unique sets of chest loot. My guess is that it's one per loot table?

**To Reproduce**
Fly around opening chests (or build around in survival like I did)
It helps if quark is installed because chests are more frequent

**Expected behavior**
Chests should generate a variety of different combinations of items.

**Screenshots**
![3 manasteel 1](https://user-images.githubusercontent.com/32604800/54075434-3b950080-426d-11e9-9be1-ad83d6e8b2c4.png)
![3 manasteel 2](https://user-images.githubusercontent.com/32604800/54075435-3b950080-426d-11e9-858b-e7e3b0143082.png)
![lexica botania 1](https://user-images.githubusercontent.com/32604800/54075436-3b950080-426d-11e9-812e-cee2a11fba6f.png)
![lexica botania 2](https://user-images.githubusercontent.com/32604800/54075437-3b950080-426d-11e9-8868-046b89930581.png)
![obsidian 1](https://user-images.githubusercontent.com/32604800/54075438-3b950080-426d-11e9-8e85-782cdd842407.png)
![obsidian 2](https://user-images.githubusercontent.com/32604800/54075439-3c2d9700-426d-11e9-9195-a22d1dc896ef.png)
![obsidian 3](https://user-images.githubusercontent.com/32604800/54075441-3cc62d80-426d-11e9-99b8-ebd5f736b713.png)
![pasta sticks 1](https://user-images.githubusercontent.com/32604800/54075445-464f9580-426d-11e9-9943-380c84db4ed6.png)
![pasta sticks 2](https://user-images.githubusercontent.com/32604800/54075444-464f9580-426d-11e9-8cfb-86ba412baec7.png)
Please note that while the screenshots I have include other mods, I've also tested this with nothing but skygrid and quark installed.

**Version**
Please list forge and mod version
Skygrid 1.1
Forge 14.23.5.2815

**Comment by PssbleTrngle** [comment]
At this point, I am not modifying the vanilla loot tables, just using them as they are. In the soon to be released version 1.2 I added a config system which lets you modify the blocks, loot, mobs and more for every single dimension. There one could add they're own loottables.

Another solution would be modifying the vanilla loottables, which I may do soon.

**Comment by PssbleTrngle** [comment]
Oh, and quark being installed should not make any difference to the frequency of chest being spawned. The way the system works is that first, it is determined _if_ should spawn a chest and then _which_ chest to spawn.

**Comment by PssbleTrngle** [comment]
Will look why it's always the same loot but I think I already know, should be fixed until tomorrow

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
