### ISSUE TITLE
Support for 1.16? Also how to get blaze rods?

### ISSUE THREAD

**Issue by Spudstak** [PssbleTrngle/Skygrid#35]
Is there any planning for the mod to be updated to 1.16 and include those new blocks in the nether? This mod is amazing and I would love to enjoy it in 1.16.

Also how would you get blaze rods in order to craft eyes of ender? When I went to the nether I couldn't find any blaze spawners. I also I ran the command it said that spawners didn't occur in the nether.

**Comment by PssbleTrngle** [comment]
I'm working on updating to 1.18 right now, but I don't plan to port it to 1.16

**Comment by Spudstak** [comment]
Oh awesome! Looking forward to it :D! I'll definitely do a video on it when you finish porting it.
