### ISSUE TITLE
Mod additions

### ISSUE THREAD

**Issue by Whottech** [PssbleTrngle/Skygrid#36]
Looking to add thermal mod mostly for ores and such.

Is this a possibility?

Or can i be shown how to and ill add them myself and such?

thanks.

**Comment by PssbleTrngle** [comment]
I am working on the 1.18 port right now, but I'll add documentation in a wiki about how to create/extend generation config files.
For now you could take a look at the [default configs](https://github.com/PssbleTrngle/Skygrid/tree/1.15.x/src/main/resources/data/minecraft/skygrid/dimensions)

**Comment by PssbleTrngle** [comment]
There is a [Wiki](https://github.com/PssbleTrngle/Skygrid/wiki) covering the 1.18.x setup.
The 1.18.1 versions are still in alpha, because the block distribution/weights are are still way of and need to be tweaked a bit
