### ISSUE TITLE
Block blacklist

### ISSUE THREAD

**Issue by azaquaz** [PssbleTrngle/Skygrid#4]
**Is your feature request related to a problem? Please describe.**
When liquids spawn, they are very messy and flow everywhere. Sometimes they remain as nonflowing source blocks, but this is not consistent at all. In particular, hot spring water from biomes o plenty never remains as a still source block.

**Describe the solution you'd like**
I can see why someone _would_ want liquids flowing down, as it makes movement through the world much easier. Rather than disabling liquid generation altogether, a blacklist for what blocks to generate would allow me to disable liquids, and it would also let modpack makers have finer control over the world. 

**Describe alternatives you've considered**
making it so hot spring water does not flow on its own would also solve this problem.

**Additional context**

**Comment by PssbleTrngle** [comment]
Thank you for your feedback.
As it happens, I've already worked on this not wanted behaviour and added a config option through which you can define the chance at which fluid blocks will spawn with invisible, replaceable blocks as a frame to keep them from flowing down.

This feature will be included in the soon to be released version 1.2 (Like tomorrow probably)
