### ISSUE TITLE
Worldtype 1.181.2

### ISSUE THREAD

**Issue by Whottech** [PssbleTrngle/Skygrid#42]
Afternoon,

Just wondering what worldtype would be for 1.18.2 - skygrid-forge-3.0.3-beta.jar

Ive tried skygrid and sky grid with no luck.

thanks!

Also i did see a bit lower in the issues that you were looking into an online editor, did this make progress or?

thanks,

Joshua

**Comment by Whottech** [comment]
found this worked - skygrid\:skygrid

Still looking into the online editor if thats a thing? having a hard time doing the datapacks is all.

**Comment by PssbleTrngle** [comment]
Yes, it should be `skygrid:skygrid`
The [online editor](https://skygrid.somethingcatchy.net/) is for now only a visualization tool. You can look at the default configs visualized, or select a local datapack directory and see your changes in real-time

**Comment by Whottech** [comment]
Is there a way to edit the default configs? without having to make a new datapack?

thanks,

Joshua

**Comment by PssbleTrngle** [comment]
No, the way to edit the default configs is to create a new datapack.
It's really not that difficult, you can take a look at the wiki and maybe the Minecraft wiki about datapacks
