### ISSUE TITLE
Loot containers aren't generating in the world

### ISSUE THREAD

**Issue by Ykaoo** [PssbleTrngle/Skygrid#45]
**Describe the bug**
Chests, trapped chests and barrels aren't generating in the world.

**To Reproduce**
Generate the world

**Expected behavior**
There should be a plenty of loot containers around the world.

**Version**
Modloader: Fabric
Modloader Version: 0.14.7
Mod Version: 3.0.4-beta

**Comment by PssbleTrngle** [comment]
Are you sure they are not generating and are not just rarer than you thought?

**Comment by Ykaoo** [comment]
Yes, I'm sure. I tried with different settings and even downgraded mod to 3.0.3. 
Checked the forge version and it works as intended.
