### ISSUE TITLE
[Suggestion] Side on value for any cardinal direction

### ISSUE THREAD

**Issue by azaquaz** [PssbleTrngle/Skygrid#46]
A lot of items in the default xml that appear on the side of a block are only set to appear on the north. Duplicating these for each cardinal direction is tedious and messy. This could be solved by having a value that picks one of north, south, east, or west at random. This wouldn't work for everything (cocoa beans for example still need to be told to face the opposing way) but it would be handy.

**Comment by PssbleTrngle** [comment]
Blocks like cocoa beans could be easily rotated in that case, so it would also be feasible for that use-case

**Comment by PssbleTrngle** [comment]
Sorry for the long wait, but this is now implemented as the new `<cardinal>` extra
