### ISSUE TITLE
Chests arent generating in the nether

### ISSUE THREAD

**Issue by Ykaoo** [PssbleTrngle/Skygrid#49]
**Describe the bug**
In the latest version chests arent generating in the nether. 

**To Reproduce**
Generate a world, go to nether and look for chests. 

**Expected behavior**
Loot 

**Version**
Modloader: both Forge and Fabric
Modloader Version: Forge 40,1.0 and Fabric 0.14.8
Mod Version: 3.0.6
No other mods used

**Comment by PssbleTrngle** [comment]
Seems like I did not add the loot pools to the nether config, will do

**Comment by PssbleTrngle** [comment]
Fixed in version 3.0.7
