### ISSUE TITLE
Forge 3.0.7 generating dafault MC world

### ISSUE THREAD

**Issue by Tangential-Text** [PssbleTrngle/Skygrid#53]
I have installed this mod in Forge with KotlinForForge3.7.1 and I get the normal world spawn.

I have tried to follow install directions but they seem to be incomplete.

**Comment by PssbleTrngle** [comment]
Have you selected the skygrid world type?

**Comment by Birbatiel** [comment]
I'm trying to run a forge server but I have this same problem, using KotlinForForge3.7.1 as well as shutupexperimentalsettings-1.0.5 as that came with skygrid on curseforge app. I try generating but it's just normal world.

here's a copy of my server.properties that I think I'm doing wrong:

generate-structures=true
generator-settings={}
level-name=world
level-seed=
level-type=skygrid

**Comment by Birbatiel** [comment]
I did find a solution to my problem, just generate a skygrid world using your client. Then uploading it to my forge world folder, it then generated for me properly.

**Comment by PssbleTrngle** [comment]
Pretty sure you'd have to either use a datapack, similar to how it's described in the wiki for other dimensions.
World Types on the server have always been a bit weird, so yes the easiest solution is probably creating the world in single player and uploading it

**Comment by PssbleTrngle** [comment]
I'll close this as unplanned for now, because implementing custom world-generation using the `server.properties` is always changing and never really worth it, I will maybe provide a datapack for it that should do the same thing in the future
