### ISSUE TITLE
Can't sleep

### ISSUE THREAD

**Issue by azaquaz** [PssbleTrngle/Skygrid#7]
Trying to sleep in a bed gives the message "you can only sleep at night" even when it is night.
Skygrid 1.2.1
Forge 14.23.5.2820

**Comment by PssbleTrngle** [comment]
That's very weird, going to look into that, thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PssbleTrngle** [comment]
Fixed all three of your reported bugs, but ran into the issue that while you now can sleep in a bed you cannot respawn at there. As soon as I solved this, I will update the mod

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
