### ISSUE TITLE
It never rains, and /weather doesn't work

### ISSUE THREAD

**Issue by azaquaz** [PssbleTrngle/Skygrid#8]
I guess I can't be *completely* sure it's not just bad rng, but it hasn't rained at all in any of my playing today, and /weather doesn't work (the weather stays clear.)
Forge 14.23.5.2820
Skygrid 1.2.1

**Comment by PssbleTrngle** [comment]
A yes, It's disabled because it caused me performance issues. Should be easy to fix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
